version: "3"
services:
  examen_mercadolibre:
    image: examen_mercadolibre
    restart: always
    ports:
      - "8080:8080"
    networks:
      - country-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:latest
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - country-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ApiGeoMeli  

networks:
  country-mysql:
     driver: bridge 